prueba/config/routes.rb
Prueba::Application.routes.draw do
  get "principal/main"
  resources :platillos

  resources :articulos

  resources :empleados

end

prueba/app/models/articulo.rb
class Articulo < ActiveRecord::Base
end

prueba/app/models/empleado.rb
class Empleado < ActiveRecord::Base
end

prueba/app/models/platillo.rb
class Platillo < ActiveRecord::Base
end

prueba/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

prueba/app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @articulo }
      else
        format.html { render action: 'new' }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:nombre, :descripcion, :precio, :stock)
    end
end

prueba/app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Se ha creado un nuevo empleado.' }
        format.json { render action: 'show', status: :created, location: @empleado }
      else
        format.html { render action: 'new' }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Empleado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:Nombre, :Direccion, :fechaEntrada)
    end
end

prueba/app/controllers/platillos_controller.rb
class PlatillosController < ApplicationController
  before_action :set_platillo, only: [:show, :edit, :update, :destroy]

  # GET /platillos
  # GET /platillos.json
  def index
    @platillos = Platillo.all
  end

  # GET /platillos/1
  # GET /platillos/1.json
  def show
  end

  # GET /platillos/new
  def new
    @platillo = Platillo.new
  end

  # GET /platillos/1/edit
  def edit
  end

  # POST /platillos
  # POST /platillos.json
  def create
    @platillo = Platillo.new(platillo_params)

    respond_to do |format|
      if @platillo.save
        format.html { redirect_to @platillo, notice: 'Platillo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @platillo }
      else
        format.html { render action: 'new' }
        format.json { render json: @platillo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platillos/1
  # PATCH/PUT /platillos/1.json
  def update
    respond_to do |format|
      if @platillo.update(platillo_params)
        format.html { redirect_to @platillo, notice: 'Platillo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @platillo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platillos/1
  # DELETE /platillos/1.json
  def destroy
    @platillo.destroy
    respond_to do |format|
      format.html { redirect_to platillos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platillo
      @platillo = Platillo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platillo_params
      params.require(:platillo).permit(:nombre, :descripcion, :precio)
    end
end

prueba/app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def main
  	@message="Hellos how are you doing?"
  end
end

prueba/app/helpers/application_helper.rb
module ApplicationHelper
end

prueba/app/helpers/articulos_helper.rb
module ArticulosHelper
end

prueba/app/helpers/empleados_helper.rb
module EmpleadosHelper
end

prueba/app/helpers/platillos_helper.rb
module PlatillosHelper
end

prueba/app/helpers/principal_helper.rb
module PrincipalHelper
end

prueba/app/views/empleados/_form.html.erb
<%= form_for(@empleado) do |f| %>
  <% if @empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% @empleado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Direccion %><br>
    <%= f.text_field :Direccion %>
  </div>
  <div class="field">
    <%= f.label :fechaEntrada %><br>
    <%= f.date_select :fechaEntrada %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

prueba/app/views/empleados/edit.html.erb
<h1>Editing empleado</h1>

<%= render 'form' %>

<%= link_to 'Ver', @empleado %> |
<%= link_to 'Regresar', empleados_path %>

prueba/app/views/empleados/index.html.erb
<h1>Lista de empleados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Fecha de entrada</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.Nombre %></td>
        <td><%= empleado.Direccion %></td>
        <td><%= empleado.fechaEntrada %></td>
        <td><%= link_to 'Ver', empleado %></td>
        <td><%= link_to 'Editar', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Eliminar', empleado, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar un nuevo Empleado', new_empleado_path %>

prueba/app/views/empleados/new.html.erb
<h1>Nuevo empleado</h1>

<%= render 'form' %>

<%= link_to 'Back', empleados_path %>

prueba/app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @empleado.Nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @empleado.Direccion %>
</p>

<p>
  <strong>Fecha entrada:</strong>
  <%= @empleado.fechaEntrada %>
</p>

<%= link_to 'Editar', edit_empleado_path(@empleado) %> |
<%= link_to 'Regresar', empleados_path %>

prueba/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tidito RT</title>
  <%= csrf_meta_tags %> 
  <%= stylesheet_link_tag "style", "application", "slider", "grid", "superfish" %>

  <%= javascript_include_tag "jquery", "jquery-migrate-1.1.1", "superfish", "jquery.easing.1.3", "sForm", "jquery.carouFredSel-6.1.0-packed", "tms-0.4.1" %>

  <script>
      $(window).load(function(){
      $('.slider')._TMS({
              show:0,
              pauseOnHover:false,
              prevBu:'.prev',
              nextBu:'.next',
              playBu:false,
              duration:800,
              preset:'fade', 
              pagination:true,//'.pagination',true,'<ul></ul>'
              pagNums:false,
              slideshow:8000,
              numStatus:false,
              banners:false,
          waitBannerAnimation:false,
        progressBar:false
      })  
      });
      
     $(window).load (
    function(){$('.carousel1').carouFredSel({auto: false,prev: '.prev',next: '.next', width: 960, items: {
      visible : {min: 1,
       max: 4
},
height: 'auto',
 width: 240,

    }, responsive: false, 
    
    scroll: 1, 
    
    mousewheel: false,
    
    swipe: {onMouse: false, onTouch: false}});
    
    
    });      

     </script>
</head>
<body>
	<div class="main">
<!--==============================header=================================-->
 <header> 
  <div class="container_12">
    <div class="grid_12">
    <h1><a href="index.html"><img src="../assets/logo.png" alt="EXTERIOR"></a> </h1>
    
         <div class="menu_block">
           <nav  class="" >
            <ul class="sf-menu">
                   <li class="current"><a href="principal/main">Inicio</a></li>
                   <li class="with_ul"><%= link_to 'Empleados', empleados_path %><ul>
                         <li><a href="#"> Chefs</a></li>
                            <li><a href="#">Camareros</a></li>
                            <li><a href="#">Cajeros</a></li>
                        
                     </ul></li>
                   <li><a href="principal/menu">Menu</a></li>
                   <li><%= link_to 'Platillos', platillos_path %></li>
                 </ul>
              </nav>
           <div class="clear"></div>
           </div>
           <div class="clear"></div>
      </div>
    </div>
</header>
 <div class="slider-relative">
    <div class="slider-block">
      <div id="slide">
        <div class="slider">
          <ul class="items">
            <li><img src="../assets/slider-1.jpg" alt=""></li>
            <li><img src="../assets/slider-2.jpg" alt=""></li>
            <li><img src="../assets/slider-3.jpg" alt=""></li>
          </ul>
        </div>
      </div>
    </div>
 </div>
<!--=======content================================-->

<div class="content page1">
	<div class="ic"></div> 
		<%= yield %>
    <div class="clear"></div>
</div>
<!--==============================footer=================================-->

<footer>    
  <div class="container_12">
  	<div class="bottom_block">
      <div class="grid_6">
        <h3>Follow Us</h3>
        <div class="socials">
          <a href="#"></a>
          <a href="#"></a>
          <a href="#"></a>
        </div>
        <nav  class="" >
            <ul class="sf-menu">
                   <li class="current"><a href="principal/main">Inicio</a></li>
                   <li class="with_ul"><%= link_to 'Empleados', empleados_path %><ul>
                         <li><a href="#"> Chefs</a></li>
                            <li><a href="#">Camareros</a></li>
                            <li><a href="#">Cajeros</a></li>
                        
                     </ul></li>
                   <li><a href="principal/menu">Menu</a></li>
                   <li><%= link_to 'Platillos', platillos_path %></li>
                 </ul>
              </nav>
      </div>
      <div class="grid_6">
        <h3>Email Updates</h3>
        <p class="col1">Join our digital mailing list and get news<br> deals and be first to know about events</p>
        <form id="newsletter">
                  <div class="success">Your subscribe request has been sent!</div>
                  <label class="email">
                       <input type="email" value="Enter e-mail address" >
                       <a href="#" class="btn" data-type="submit">subscribe</a> 
                        <span class="error">*This is not a valid email address.</span>
                  </label> 
              </form> 
          </div>
      </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
</footer>
</body>
</html>

prueba/app/views/platillos/_form.html.erb
<%= form_for(@platillo) do |f| %>
  <% if @platillo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platillo.errors.count, "error") %> prohibited this platillo from being saved:</h2>

      <ul>
      <% @platillo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

prueba/app/views/platillos/edit.html.erb
<h1>Editing platillo</h1>

<%= render 'form' %>

<%= link_to 'Show', @platillo %> |
<%= link_to 'Back', platillos_path %>

prueba/app/views/platillos/index.html.erb
<h1>Listing platillos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.descripcion %></td>
        <td><%= platillo.precio %></td>
        <td><%= link_to 'Show', platillo %></td>
        <td><%= link_to 'Edit', edit_platillo_path(platillo) %></td>
        <td><%= link_to 'Destroy', platillo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a class="yellow-button"><%= link_to 'New Platillo', new_platillo_path %></a>

prueba/app/views/platillos/new.html.erb
<h1>New platillo</h1>

<%= render 'form' %>

<%= link_to 'Back', platillos_path %>

prueba/app/views/platillos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @platillo.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @platillo.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @platillo.precio %>
</p>

<%= link_to 'Edit', edit_platillo_path(@platillo) %> |
<%= link_to 'Back', platillos_path %>

prueba/app/views/principal/main.html.erb
<h1>A greeting for you</h1>
<p><%= @message %></p>